/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package p001;

import static org.junit.Assert.*;


public class CatTest {
    // @Test
    // public void testAppHasAGreeting() {
    //     Cat classUnderTest = new Cat();
    // }
}
